language: android
dist: trusty
sudo: true
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - android-28
    - build-tools-28.0.3
    - platform-tools
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  bundler : true
  directories:
    - "${TRAVIS_BUILD_DIR}/gradle/caches/"
    - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

install:
  - bundle install

before_script:
  - bash scripts/prep-key.sh
  - bash scripts/check-screenshots.sh

script:
  - ./gradlew spotlessCheck
  - ./gradlew build --stacktrace

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/upload-apk.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|development)$
  - provider: script
    skip_cleanup: true
    script: bash scripts/upload-gh-pages.sh
    on:
      all_branches: true
