jobs:
  include:
    - name: Build Android
      language: android
      dist: trusty
      sudo: true
      jdk:
        - oraclejdk8
      android:
        components:
          - tools
          - android-29
          - build-tools-29.0.2
          - platform-tools
      before_cache:
        - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
      cache:
        bundler: true
        directories:
          - "${TRAVIS_BUILD_DIR}/gradle/caches/"
          - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
          - "$HOME/.gradle/caches/"
          - "$HOME/.gradle/wrapper/"

      install:
        - bundle install

      before_script:
        - bash scripts/prep-key.sh
        - bash scripts/check-screenshots.sh

      script:
        - ./gradlew spotlessCheck
        - ./gradlew build --stacktrace
        - ./gradlew :BadgeMagicModule:packForXcode --stacktrace

      deploy:
        - provider: script
          skip_cleanup: true
          script: bash scripts/upload-apk.sh
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^(master|development)$
            repo: fossasia/badge-magic-android
        - provider: script
          skip_cleanup: true
          script: bash scripts/upload-gh-pages.sh
          on:
            all_branches: true
            repo: fossasia/badge-magic-android
    - name: Build iOS
      os: osx
      osx_image: xcode11.3
      language: objective-c

      before_cache:
        - brew cleanup

      cache:
        bundler: true
        directories:
          - $HOME/.konan
          - $HOME/Library/Caches/Homebrew

      before_script:
        # Java Installation
        - java -version
        - sudo rm -rf /Library/Java/*
        - sudo rm -rf /Library/PreferencePanes/Java*
        - sudo rm -rf /Library/Internet\ Plug-Ins/Java*
        - brew tap AdoptOpenJDK/openjdk
        - brew cask install adoptopenjdk8
        - java -version
        # -----------
        # -----------
        # Remove Project from gradle.settings
        - echo "include ':BadgeMagicModule'" > settings.gradle
        # -----------
        - brew install swiftlint
        - ./gradlew BadgeMagicModule:packForXcode --stacktrace
        - cp -r BadgeMagicModule/build/xcode-frameworks/BadgeMagicModule.framework iOS/badgemagic

      script:
        - cd iOS
        - bundle exec fastlane run swiftlint strict:"true"
        - bundle exec fastlane gym --skip_codesigning --skip_archive --skip_package_ipa

      deploy:
        - provider: script
          skip_cleanup: true
          script: bash scripts/upload-ios-framework.sh
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^(master|development)$
            repo: fossasia/badge-magic-android